// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ConfigPolygonJs = require("./raw/config-polygon.js");
var ConfigAvalancheJs = require("./raw/config-avalanche.js");

var avalancheConfig = ConfigAvalancheJs.config;

var polygonConfig = ConfigPolygonJs.config;

exports.avalancheConfig = avalancheConfig;
exports.polygonConfig = polygonConfig;
/* avalancheConfig Not a pure module */
