// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ConfigPolygonJs = require("./raw/config-polygon.js");
var ConfigAvalancheJs = require("./raw/config-avalanche.js");

var avalancheConfig = ConfigAvalancheJs.config;

var polygonConfig = ConfigPolygonJs.config;

function getChainConfig(chainId) {
  if (avalancheConfig.networkId === chainId) {
    return avalancheConfig;
  } else if (polygonConfig.networkId === chainId) {
    return polygonConfig;
  } else {
    return ;
  }
}

exports.avalancheConfig = avalancheConfig;
exports.polygonConfig = polygonConfig;
exports.getChainConfig = getChainConfig;
/* avalancheConfig Not a pure module */
