// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ConfigAvalancheJs = require("./raw/config-avalanche.js");

var avalanche = ConfigAvalancheJs.config;

exports.avalanche = avalanche;
/* avalanche Not a pure module */
